[tool.ruff]
src = ["src", "tests"]
line-length = 79

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 72

#[tool.black]
#line-length = 79
#target-version = ['py310']
#
## Исключение для всей папки migrations и файла env.py
#exclude = '''
#/(
#    src/migrations/env\.py
#)/
#'''
#
#[tool.isort]
#profile = "black"
#skip = ["src/migrations", "src/migrations/env.py"]