"""Автоматическое проставление поля created_at в ДБ

Revision ID: eb70e267353a
Revises: 8a93a40d24a9
Create Date: 2025-06-15 09:22:36.644462

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb70e267353a"
down_revision: Union[str, None] = "8a93a40d24a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
