services:
  postgres:
    image:  ${PG_VERSION}
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_NAME}
    volumes:
      - ./postgres-data:${PG_DATA}
    ports:
      - "${PG_PORT}:5432"
    restart: unless-stopped
    networks:
      - network_course


networks:
  network_course:
    driver: bridge